-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRODUCT.PRICE * SALE.SALES_AMOUNT) AS SALES
FROM PRODUCT
JOIN OFFLINE_SALE SALE ON SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE


/*
온라인 - PRODUCT
오프라인 할인제품 -OFFLINE_SALE

상품코드 고유한 값.
상품코드별 매출액(판매가 * 판매량)출력. 매출액 기준 내림차순 상품코드 오름차순 정렬
*/