SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
LEFT JOIN ANIMAL_INS INS ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.INTAKE_CONDITION IS NULL
ORDER BY OUTS.ANIMAL_ID

/*
보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID순 조회
*/